// SOLVEN4 Door configuration — update URLs to match your deployed/local environments
export const DOORS = [
  {
    id: 'edge',
    code: 'S4-I',
    name: 'S4 EDGE',
    fullName: 'SOLVEN4 EDGE',
    subtitle: "The Trader's Weapon",
    tagline: 'Signal. Execute. Dominate.',
    desc: 'Real-time signals, trade journal, MT5 integration, AI coaching, and TradingDNA. Your edge — sharpened to a blade.',
    features: ['Signal Tracker', 'Trade Journal', 'MT5 Integration', 'AI Coach', 'TradingDNA', 'Backtesting', 'GlitchBox', 'Weekly Briefing'],
    color: '#3B82F6',
    colorKey: 'edge',
    textClass: 'text-s4-edge',
    borderClass: 'border-s4-edge/30',
    bgClass: 'bg-s4-edge/5',
    glowClass: 'hover:shadow-[0_0_60px_rgba(59,130,246,0.2)]',
    badgeClass: 'bg-s4-edge/20 text-s4-edge border border-s4-edge/30',
    gradient: 'from-s4-edge/20 via-s4-edge/5 to-transparent',
    href: 'https://solven4-edge-six.vercel.app',
    users: '2.4K',
    stat: '1,240 signals this week',
  },
  {
    id: 'forge',
    code: 'S4-II',
    name: 'S4 FORGE',
    fullName: 'SOLVEN4 FORGE',
    subtitle: "The Dealer's Empire",
    tagline: 'Refer. Earn. Expand.',
    desc: 'Full IB command center — network tree, commissions, WhatsApp & Telegram automation, AI lead intelligence, and arena challenges.',
    features: ['Network Hub', 'Commission Engine', 'WhatsApp Broadcast', 'Telegram Bot', 'Lead Intelligence', 'Arena XP', 'AI Tools (8)', 'Referral Funnels'],
    color: '#D4A843',
    colorKey: 'forge',
    textClass: 'text-s4-forge',
    borderClass: 'border-s4-forge/30',
    bgClass: 'bg-s4-forge/5',
    glowClass: 'hover:shadow-[0_0_60px_rgba(212,168,67,0.2)]',
    badgeClass: 'bg-s4-forge/20 text-s4-forge border border-s4-forge/30',
    gradient: 'from-s4-forge/20 via-s4-forge/5 to-transparent',
    href: 'https://solven4-forge-pi.vercel.app',
    users: '3.8K',
    stat: '$48K commissions paid',
  },
  {
    id: 'oracle',
    code: 'S4-III',
    name: 'S4 ORACLE',
    fullName: 'SOLVEN4 ORACLE',
    subtitle: "The Legend's Library",
    tagline: 'Learn. Evolve. Ascend.',
    desc: 'Intelligence engine, learning paths, market analysis, whale tracking, sentiment engine, and macro intelligence — knowledge weaponized.',
    features: ['Intelligence Engine', 'Learning Paths', 'Whale Tracker', 'Sentiment Engine', 'Macro Engine', 'Market Analysis', 'Financial News', 'Broadcasts'],
    color: '#10B981',
    colorKey: 'oracle',
    textClass: 'text-s4-oracle',
    borderClass: 'border-s4-oracle/30',
    bgClass: 'bg-s4-oracle/5',
    glowClass: 'hover:shadow-[0_0_60px_rgba(16,185,129,0.2)]',
    badgeClass: 'bg-s4-oracle/20 text-s4-oracle border border-s4-oracle/30',
    gradient: 'from-s4-oracle/20 via-s4-oracle/5 to-transparent',
    href: 'https://solven4-oracle-eight.vercel.app',
    users: '5.1K',
    stat: '340 lessons published',
  },
  {
    id: 'nexus',
    code: 'S4-IV',
    name: 'S4 NEXUS',
    fullName: 'SOLVEN4 NEXUS',
    subtitle: "The Operator's Control Room",
    tagline: 'Automate. Scale. Command.',
    desc: 'CRM, content studio, automation flows, AI agents, income visualizer, campaign manager — run your entire trading business.',
    features: ['CRM & Leads', 'Content Studio', 'AI Agents', 'Automation Flows', 'Income Visualizer', 'Campaigns', 'Social Accounts', 'Resource Hub'],
    color: '#EF4444',
    colorKey: 'nexus',
    textClass: 'text-s4-nexus',
    borderClass: 'border-s4-nexus/30',
    bgClass: 'bg-s4-nexus/5',
    glowClass: 'hover:shadow-[0_0_60px_rgba(139,92,246,0.2)]',
    badgeClass: 'bg-s4-nexus/20 text-s4-nexus border border-s4-nexus/30',
    gradient: 'from-s4-nexus/20 via-s4-nexus/5 to-transparent',
    href: 'https://solven4-nexus-self.vercel.app',
    users: '1.9K',
    stat: '820 automations running',
  },
];
